from pymol import cmd
cmd.reinitialize()
cmd.bg_color("white")
cmd.load(r"test_aligners/aligned_pdbs/1j8h_aligned.pdb", "1j8h_aligned")
cmd.load(r"test_aligners/aligned_pdbs/1fyt_aligned.pdb", "1fyt_aligned")
cmd.load(r"test_aligners/aligned_pdbs/1g6r_aligned.pdb", "1g6r_aligned")
cmd.hide("everything", "all")
cmd.show("cartoon", "1j8h_aligned")
cmd.color("cyan", "1j8h_aligned")
cmd.show("cartoon", "1fyt_aligned")
cmd.color("green", "1fyt_aligned")
cmd.show("cartoon", "1g6r_aligned")
cmd.color("orange", "1g6r_aligned")
cmd.select("align_1j8h_aligned", "1j8h_aligned and ((chain A and resi 18+20+3-10) or (chain B and resi 1-4+5-10))")
cmd.select("score_1j8h_aligned", "1j8h_aligned and ((chain A and resi 18+22+5-10))")
cmd.color("tv_yellow", "align_1j8h_aligned")
cmd.color("magenta", "score_1j8h_aligned")
cmd.select("align_1fyt_aligned", "1fyt_aligned and ((chain A and resi 18+20+3-10) or (chain B and resi 1-4+5-10))")
cmd.select("score_1fyt_aligned", "1fyt_aligned and ((chain A and resi 18+22+5-10))")
cmd.color("tv_yellow", "align_1fyt_aligned")
cmd.color("magenta", "score_1fyt_aligned")
cmd.select("align_1g6r_aligned", "1g6r_aligned and ((chain A and resi 18+20+3-10) or (chain B and resi 1-4+5-10))")
cmd.select("score_1g6r_aligned", "1g6r_aligned and ((chain A and resi 18+22+5-10))")
cmd.color("tv_yellow", "align_1g6r_aligned")
cmd.color("magenta", "score_1g6r_aligned")
mn, mx = cmd.get_extent("all")
dx = mx[0]-mn[0]; dy = mx[1]-mn[1]; dz = mx[2]-mn[2]
p_align = [mn[0] + 0.06*dx, mx[1] - 0.06*dy, mx[2] - 0.06*dz]
p_score = [mn[0] + 0.06*dx, mx[1] - 0.14*dy, mx[2] - 0.06*dz]
cmd.pseudoatom("legend_align", pos=p_align)
cmd.pseudoatom("legend_score", pos=p_score)
cmd.show("spheres", "legend_align or legend_score")
cmd.set("sphere_scale", 1, "legend_align or legend_score")
cmd.color("tv_yellow", "legend_align")
cmd.color("magenta", "legend_score")
cmd.set("label_color", "black")
cmd.set("label_size", 18)
cmd.set("label_position", [1.5, 0.0, 0.0])
cmd.set("label_outline_color", "white")
cmd.label("legend_align", "'Aligned region'")
cmd.label("legend_score", "'Scored region'")
cmd.set("cartoon_transparency", 0.15, "all")
cmd.orient("all")
cmd.zoom("all", 1.15)
cmd.png(r"test_aligners/aligned_overlay.png", dpi=300, ray=1)
cmd.save(r"test_aligners/aligned_overlay.pse")
cmd.quit()